# ontology.py

# Wikidata Relation Definitions
# Used for context generation and anchor fetching strategy
WIKIDATA_RELATIONS = {
    "P17": "Country (The country where the item is located)",
    "P19": "Place of birth (The location where the person was born)",
    "P20": "Place of death (The location where the person died)",
    "P27": "Country of citizenship",
    "P30": "Continent",
    "P31": "Instance of (The class of which this item is an instance)",
    "P36": "Capital (The capital city of the country/region)",
    "P37": "Official language",
    "P47": "Shares border with",
    "P50": "Author (The person who wrote the work)",
    "P57": "Director (The person who directed the film/play)",
    "P86": "Composer (The person who wrote the music)",
    "P101": "Field of work (The domain the person works in)",
    "P103": "Native language",
    "P106": "Occupation (The job or profession of the person)",
    "P108": "Employer (The company the person works for)",
    "P127": "Owned by (The owner of the entity)",
    "P131": "Located in the administrative territorial entity",
    "P136": "Genre (The style of music/art)",
    "P138": "Named after",
    "P140": "Religion",
    "P159": "Headquarters location",
    "P170": "Creator (The maker of the creative work)",
    "P176": "Manufacturer (The company that produced the product)",
    "P178": "Developer (The company/person that developed the software)",
    "P190": "Twinned administrative body (Sister cities)",
    "P264": "Record label",
    "P276": "Location (Where the object is located)",
    "P361": "Part of",
    "P449": "Original broadcaster/Network (The TV channel where it first aired)",
    "P463": "Member of (Organization membership)",
    "P495": "Country of origin (Where the work/product was created)",
    "P527": "Has part (The entity is composed of these parts)",
    "P740": "Location of formation (Where the band/group started)",
    "P937": "Work location",
    "P1001": "Applies to jurisdiction",
    "P1303": "Instrument (The musical instrument played)",
    "P1376": "Capital of",
    "P1412": "Languages spoken, written or signed",
    # Add more as needed
}